### ISSUE TITLE
Chromecast skipping

### ISSUE THREAD

**Issue by jeromegn** [mdhiggins/PlexAutoSkip#19]
I've had success using your project for skipping an intro when playing something on my iPhone, but not if I'm chromecasting it.

(I also can't make it work the web client on Safari, getting bad requests but none of the troubleshooting instructions helped, unfortunately)

Logs:

```
INFO - Found new session 26 [2085] (Star Trek s01e15 - Shore Leave) Chromecast viewOffset 0 ['jeromegn'], sessions: 0
INFO - Seeking Plex Cast player playing 26 [2085] (Star Trek s01e15 - Shore Leave) Chromecast from 253774 to 253765
ERROR - Exception, removing from cache to prevent false triggers, will be restored with next sync
Traceback (most recent call last):
  File "/home/jerome/PlexAutoSkip/resources/skipper.py", line 226, in seekPlayerTo
    player.seekTo(targetOffset)
  File "/home/jerome/.local/lib/python3.10/site-packages/plexapi/client.py", line 376, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "/home/jerome/.local/lib/python3.10/site-packages/plexapi/client.py", line 231, in sendCommand
    return query(key, headers=headers)
  File "/home/jerome/.local/lib/python3.10/site-packages/plexapi/server.py", line 706, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://192-168-1-143.1c9f2570de0944798243bb96a7bae443.plex.direct:32400/player/playback/seekTo?commandID=1&offset=253765&type=video <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier cu8v7az0uxdccztdklv9cseo">   <Traceback>Traceback (most recent call last):   File "/usr/lib/plexmediaserver/Resources/Plug-ins-c8bd13540/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request     result = f(**d)   File "/usr/lib/plexmediaserver/Resources/Plug-ins-c8bd13540/System.bundle/Contents/Code/playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier cu8v7az0uxdccztdklv9cseo </Traceback> </Response>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0ca37b0790>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.8', port=32500): Max retries exceeded with url: /player/playback/seekTo?commandID=2&offset=253765&type=video (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ca37b0790>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jerome/PlexAutoSkip/resources/skipper.py", line 199, in _seekTo
    self.seekPlayerTo(player, mediaWrapper, targetOffset)
  File "/home/jerome/PlexAutoSkip/resources/skipper.py", line 233, in seekPlayerTo
    return self.seekPlayerTo(self.recoverPlayer(player), mediaWrapper, targetOffset)
  File "/home/jerome/PlexAutoSkip/resources/skipper.py", line 226, in seekPlayerTo
    player.seekTo(targetOffset)
  File "/home/jerome/.local/lib/python3.10/site-packages/plexapi/client.py", line 376, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "/home/jerome/.local/lib/python3.10/site-packages/plexapi/client.py", line 231, in sendCommand
    return query(key, headers=headers)
  File "/home/jerome/.local/lib/python3.10/site-packages/plexapi/client.py", line 182, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.8', port=32500): Max retries exceeded with url: /player/playback/seekTo?commandID=2&offset=253765&type=video (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ca37b0790>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by mdhiggins** [comment]
This is failure of both the GDM / proxyThroughServer API call along with the direct IP connection fallback method and unfortunately if the troubleshooting steps don't work, I don't have much more to offer in the way of a fix. Ultimately these errors are not errors directly related to my script but to the PlexAPI attempts to send commands

If you are able to get any of the plexAPI commands working on the chromecast I'm happy to integrate the solution you find but this is really a failure of an external library so you may be better off asking on their github if there are any suggestions

You can potentially look at your plex logs while casting to the chromecast and see if it's reporting a different port (32500 is the default fallback port) and then try custom defining that player using that alternate port but I'm fairly certain the chromecast - like the web player -  doesn't support direct IP connection fallback anyway

**Comment by mdhiggins** [comment]
Also, are you using docker?

If so, try setting the container to "host" networking mode

See this issue that skippex had solved this change, error message is similar

https://github.com/sprt/skippex/commit/a7e97aaa7076c8d23d41818026b44fb0e8f58896

**Comment by jeromegn** [comment]
Thanks for the response!

I'm not using Docker.

So I think this is because chromecasting from my phone "changes" the client and that one isn't advertised as a player?

For now I just installed the official Plex app on my Chromecast and used that. Worked fine!

Thanks a bunch of this project!

**Comment by mdhiggins** [comment]
I think its just a limitation of the Plex Cast app that gets used when casting, it doesn't have full API support

**Comment by mdhiggins** [comment]
Didn't know you could install apps on a chromecast now though, haven't used one since the original

Good to know this is a potential solution, thanks for sharing
