### ISSUE TITLE
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by habskilla** [mdhiggins/PlexAutoSkip#2]
Changed logging to debug but nothing was caught.

I see this from the main.py:
`INFO - /usr/bin/python3
INFO - Loading config file /opt/PlexAutoSkip/config/config.ini.
INFO - Connected to Plex server BEAST using plex.tv account
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    intro_skipper.start(sslopt=sslopt)
  File "/opt/PlexAutoSkip/resources/introSkipper.py", line 38, in start
    self.listener = SSLAlertListener(self.server, self.processAlert, self.error, sslopt=sslopt)
  File "/opt/PlexAutoSkip/resources/sslAlertListener.py", line 19, in __init__
    super(SSLAlertListener, self).__init__(server, callback, callbackError)
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given`

**Comment by mdhiggins** [comment]
Looks like you might be on an older version of the python-plexapi, they added the 4 parameters in November of 2021

[15e011fd291ecfb7d9da1e1596cb421e74ec8b9f](https://github.com/pkkid/python-plexapi/commit/15e011fd291ecfb7d9da1e1596cb421e74ec8b9f#diff-d7b9cf00531385452f3466e4a62524089a6d23c0a5d796ed28a333fd06b97b84)

Try updating using

`pip install --upgrade plexapi`

**Comment by mdhiggins** [comment]
Added backwards compatibility and included a log message recommending updating if users encounter this issue, going to close this out for now but please reopen with any issues

**Comment by habskilla** [comment]
`pip install --upgrade plexapi` resolved the issue.
