### ISSUE TITLE
Recurring error on startup - 'socket' object has no attribute 'pending'

### ISSUE THREAD

**Issue by doctarrwho** [mdhiggins/PlexAutoSkip#23]
Starting to see this on startup lately, only started happening in the last couple of days, and repeats over and over. 

```
today at 9:22:14 PMINFO - Connected to Plex server XXXXX using server settings
today at 9:22:31 PMINFO - Skipper initiated and ready
today at 9:22:31 PMWARNING - websocket connected
today at 9:22:31 PMERROR - 'socket' object has no attribute 'pending'
today at 9:22:31 PMINFO - websocket disconnected (retrying in 5 seconds) [6 frames in stack]
today at 9:22:31 PMException in thread Thread-1:
today at 9:22:31 PMTraceback (most recent call last):
today at 9:22:31 PM  File "/usr/local/pas/venv/lib/python3.9/site-packages/websocket/_app.py", line 354, in setSock
today at 9:22:31 PM    dispatcher.read(self.sock.sock, read, check)
today at 9:22:31 PM  File "/usr/local/pas/venv/lib/python3.9/site-packages/websocket/_app.py", line 70, in read
today at 9:22:31 PM    r = self.select()
today at 9:22:31 PM  File "/usr/local/pas/venv/lib/python3.9/site-packages/websocket/_app.py", line 78, in select
today at 9:22:31 PM    if sock.pending():
today at 9:22:31 PMAttributeError: 'socket' object has no attribute 'pending'
today at 9:22:31 PM
today at 9:22:31 PMDuring handling of the above exception, another exception occurred:
today at 9:22:31 PM
today at 9:22:31 PMTraceback (most recent call last):
today at 9:22:31 PM  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
today at 9:22:31 PM    self.run()
today at 9:22:31 PM  File "/usr/local/pas/resources/sslAlertListener.py", line 37, in run
today at 9:22:31 PM    self._ws.run_forever(sslopt=self._sslopt)
today at 9:22:31 PM  File "/usr/local/pas/venv/lib/python3.9/site-packages/websocket/_app.py", line 420, in run_forever
today at 9:22:31 PM    setSock()
today at 9:22:31 PM  File "/usr/local/pas/venv/lib/python3.9/site-packages/websocket/_app.py", line 356, in setSock
today at 9:22:31 PM    handleDisconnect(e)
today at 9:22:31 PM  File "/usr/local/pas/venv/lib/python3.9/site-packages/websocket/_app.py", line 407, in handleDisconnect
today at 9:22:31 PM    dispatcher.timeout(reconnect, setSock)
today at 9:22:31 PMAttributeError: 'SSLDispatcher' object has no attribute 'timeout'
today at 9:22:32 PMWARNING - websocket connected
```

**Comment by mdhiggins** [comment]
Hm looks like a weird websocket error, are you still seeing this on the latest image? I'm not able to reproduce

**Comment by doctarrwho** [comment]
I had ssl setting set to False under [Server] and got the failure. I just tried setting it to True, and it doesn't throw these failures.
