### ISSUE TITLE
Recursive error occurred

### ISSUE THREAD

**Issue by lhg1026** [mdhiggins/PlexAutoSkip#55]
How to handle recursive errors that occur when running on both Synology DSM7.1 and OpenWRT?

Traceback (most recent call last):
  File "/mnt/nvme0n1-4/plex/PlexAutoSkip-master/main.py", line 27, in <module>
    skipper.start(sslopt=sslopt)
  File "/mnt/nvme0n1-4/plex/PlexAutoSkip-master/resources/skipper.py", line 105, in start
    self.start(sslopt)
  File "/mnt/nvme0n1-4/plex/PlexAutoSkip-master/resources/skipper.py", line 105, in start
    self.start(sslopt)
  File "/mnt/nvme0n1-4/plex/PlexAutoSkip-master/resources/skipper.py", line 105, in start
    self.start(sslopt)
  [Previous line repeated 987 more times]
  File "/mnt/nvme0n1-4/plex/PlexAutoSkip-master/resources/skipper.py", line 90, in start
    self.listener = SSLAlertListener(self.server, self.processAlert, self.error, sslopt=sslopt, logger=self.log)
  File "/mnt/nvme0n1-4/plex/PlexAutoSkip-master/resources/sslAlertListener.py", line 23, in __init__
    super(SSLAlertListener, self).__init__(server, callback, callbackError)
  File "/usr/lib/python3.10/site-packages/plexapi/alert.py", line 42, in __init__
    super(AlertListener, self).__init__()
  File "/usr/lib/python3.10/threading.py", line 876, in __init__
  File "/usr/lib/python3.10/threading.py", line 546, in __init__
  File "/usr/lib/python3.10/threading.py", line 258, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by mdhiggins** [comment]
8f3a76bca095b10be5ff57d9cd3116d6957cbe59

This should at least prevent the recursive loop issue but the main problem here is your connection isn't working

The `while self.listener.is_alive():` call is returning false immediately (and creating the infinite retry loop) so your connection to your plex server via the plex api listener will need some troubleshooting
