### ISSUE TITLE
fails to skip for roku client

### ISSUE THREAD

**Issue by dnikles** [mdhiggins/PlexAutoSkip#6]
Here is a relevant part of the logs. It finds the intro but is unable to skip.

```
INFO - Found an intro marker for media 40 [19134] (It's Always Sunny in Philadelphia s01e06 - The Gang Finds A Dead Guy) Living room with range 64890-88235 and viewOffset 65122
ERROR - Error seeking
Traceback (most recent call last):
  File "/usr/local/pas/resources/introSkipper.py", line 140, in checkPlayerForMedia
    return not player.timeline or (player.isPlayingMedia(False) and player.timeline.key == media.key)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 584, in timeline
    return next((x for x in self.timelines() if x.state != 'stopped'), None)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 576, in timelines
    timelines = self.sendCommand(ClientTimeline.key, wait=wait) or []
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 231, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://192-168-2-95.8b9e77ceda2941d3a1bd538fe151daba.plex.direct:32400/player/timeline/poll?commandID=1&wait=0 <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier 41c403359976dbcfb82f6c700be4534b">   <Traceback>Traceback (most recent call last):   File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request     result = f(**d)   File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/System.bundle/Contents/Code/playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 41c403359976dbcfb82f6c700be4534b </Traceback> </Response> 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f4f725283c8>, 'Connection to 192.168.2.118 timed out. (connect timeout=30)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/pas/venv/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/pas/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.2.118', port=32500): Max retries exceeded with url: /resources (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4f725283c8>, 'Connection to 192.168.2.118 timed out. (connect timeout=30)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/pas/resources/introSkipper.py", line 104, in seekTo
    if self.checkPlayerForMedia(player, mediaWrapper.media):
  File "/usr/local/pas/resources/introSkipper.py", line 149, in checkPlayerForMedia

    raise(e)
  File "/usr/local/pas/resources/introSkipper.py", line 144, in checkPlayerForMedia
    player = self.recoverPlayer(player)
  File "/usr/local/pas/resources/introSkipper.py", line 159, in recoverPlayer
    return PlexClient(self.server, baseurl=baseurl, token=self.server._token)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 81, in __init__
    self.connect(timeout=timeout)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 95, in connect
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 182, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.2.118', port=32500): Max retries exceeded with url: /resources (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4f725283c8>, 'Connection to 192.168.2.118 timed out. (connect timeout=30)'))

```

**Comment by mdhiggins** [comment]
Try updating to the latest version I made a few attempts to address these errors already

Also see issue #3 and https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting

**Comment by dnikles** [comment]
Thanks for the suggestions. I think the roku client is an entirely different beast though. I did a docker pull on this moments before I opened the bug report. I do have gdm enabled. Roku client does not advertise as a player. FWIW, I had the same issue with skippex.

**Comment by mdhiggins** [comment]
I pretty much did all my development and testing on roku and its working without any issues on my end

**Comment by mdhiggins** [comment]
Do you have the `Remote Control` option turned on in your Plex Roku app under Settings > General?

**Comment by dnikles** [comment]
That's excellent news! But I'm not sure what issue I'm running into then. Yes, I do have Remote Control turned on.

**Comment by dnikles** [comment]
There aren't a lot of options, but one thing I don't have that may not be as common is I do NOT have "automatically sign in" enabled

**Comment by mdhiggins** [comment]
I don't either, that shouldn't matter, this is probably still a GDM issue, I tried turning GDM off and I'm getting a similar error as you on my roku clients, the workaround I have for Android TV isn't working on Roku when GDM fails, I wonder if roku uses a different port

**Comment by dnikles** [comment]
Admittedly, I'm not familiar with what GDM is. Is that run from the server end or the client end? I do have GDM enabled on both the server and the client as far as I can tell. I'm running plex in docker and wondering if I'm not publishing a needed port for this.

**Comment by mdhiggins** [comment]
If you're running your plex docker container in HOST networking mode it shouldn't matter, if not, then yeah you might need to open up some ports
GDM is a network discovery protocol

https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/

> TCP: 8324 (controlling Plex for Roku via Plex Companion)
> UDP: 32410, 32412, 32413, 32414 (current GDM network discovery

**Comment by dnikles** [comment]
yeah I have all of the ports open.
I see on the last line of the log I posted, it's trying to connect to the roku on port 32500. It knows where the roku is. Makes me think the issue is on my roku clients.

**Comment by mdhiggins** [comment]
Nah I hardcoded that as the fallback port for the plex client when GDM fails, that's the default port for a number of plex clients but I'm not sure its universal

What's your plex docker container command/compose look like?

**Comment by dnikles** [comment]
It's basically the default config plex provides for bridge networking on docker
```
docker run \
-d \
--name plex \
-p 32400:32400/tcp \
-p 3005:3005/tcp \
-p 8324:8324/tcp \
-p 32469:32469/tcp \
-p 1900:1900/udp \
-p 32410:32410/udp \
-p 32412:32412/udp \
-p 32413:32413/udp \
-p 32414:32414/udp \
-e TZ="<timezone>" \
-e PLEX_CLAIM="<claimToken>" \
-e ADVERTISE_IP="http://<hostIPAddress>:32400/" \
-h <HOSTNAME> \
-v <path/to/plex/database>:/config \
-v <path/to/transcode/temp>:/transcode \
-v <path/to/media>:/data \
plexinc/pms-docker
```

**Comment by mdhiggins** [comment]
Alright I did some testing and it looks like Roku does use port 8324 for plex controls instead of 32500 like Android and other clients

I improved my approach to the direct connect fallback and will dynamically adjust the port for roku devices, try updating to the latest pull and see if things work, I was able to get my Roku to work with GDM turned off using the latest build

Tip: You can set the env variable PAS_UPDATE=true for the docker container and that will update the repo from github on restart without needing to wait for the container to rebuild

**Comment by dnikles** [comment]
That worked! Thanks for all of your help!
