### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by xelemorf** [mdhiggins/PlexAutoSkip#67]
When executing main.py I have the following errmsg; would you be able to please assist me on how to fix this?I have just installed this, so I have the latest available version for all dependencies.
```

py.exe .\main.py
Traceback (most recent call last):
  File "C:\Users\user\documents\apps\PlexAutoSkip\main.py", line 6, in <module>
    from resources.skipper import Skipper
  File "C:\Users\user\documents\apps\PlexAutoSkip\resources\skipper.py", line 23, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by xelemorf** [comment]
Okay, it seems I have fixed it using the below command:
`python -m pip install --upgrade pip setuptools`
